// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file GripperSensor_msg.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "GripperSensor_msg.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

idl_msg::GripperSensor_msg::GripperSensor_msg()
{
    // m_force_front_left com.eprosima.idl.parser.typecode.PrimitiveTypeCode@dd3b207
    m_force_front_left = 0;
    // m_force_front_right com.eprosima.idl.parser.typecode.PrimitiveTypeCode@551bdc27
    m_force_front_right = 0;
    // m_force_back_left com.eprosima.idl.parser.typecode.PrimitiveTypeCode@58fdd99
    m_force_back_left = 0;
    // m_force_back_right com.eprosima.idl.parser.typecode.PrimitiveTypeCode@6b1274d2
    m_force_back_right = 0;

}

idl_msg::GripperSensor_msg::~GripperSensor_msg()
{




}

idl_msg::GripperSensor_msg::GripperSensor_msg(
        const GripperSensor_msg& x)
{
    m_force_front_left = x.m_force_front_left;
    m_force_front_right = x.m_force_front_right;
    m_force_back_left = x.m_force_back_left;
    m_force_back_right = x.m_force_back_right;
}

idl_msg::GripperSensor_msg::GripperSensor_msg(
        GripperSensor_msg&& x)
{
    m_force_front_left = x.m_force_front_left;
    m_force_front_right = x.m_force_front_right;
    m_force_back_left = x.m_force_back_left;
    m_force_back_right = x.m_force_back_right;
}

idl_msg::GripperSensor_msg& idl_msg::GripperSensor_msg::operator =(
        const GripperSensor_msg& x)
{

    m_force_front_left = x.m_force_front_left;
    m_force_front_right = x.m_force_front_right;
    m_force_back_left = x.m_force_back_left;
    m_force_back_right = x.m_force_back_right;

    return *this;
}

idl_msg::GripperSensor_msg& idl_msg::GripperSensor_msg::operator =(
        GripperSensor_msg&& x)
{

    m_force_front_left = x.m_force_front_left;
    m_force_front_right = x.m_force_front_right;
    m_force_back_left = x.m_force_back_left;
    m_force_back_right = x.m_force_back_right;

    return *this;
}

bool idl_msg::GripperSensor_msg::operator ==(
        const GripperSensor_msg& x)
{

    return (m_force_front_left == x.m_force_front_left && m_force_front_right == x.m_force_front_right && m_force_back_left == x.m_force_back_left && m_force_back_right == x.m_force_back_right);
}

bool idl_msg::GripperSensor_msg::operator !=(
        const GripperSensor_msg& x)
{
    return !(*this == x);
}

size_t idl_msg::GripperSensor_msg::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

size_t idl_msg::GripperSensor_msg::getCdrSerializedSize(
        const idl_msg::GripperSensor_msg& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

void idl_msg::GripperSensor_msg::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_force_front_left;
    scdr << m_force_front_right;
    scdr << m_force_back_left;
    scdr << m_force_back_right;

}

void idl_msg::GripperSensor_msg::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_force_front_left;
    dcdr >> m_force_front_right;
    dcdr >> m_force_back_left;
    dcdr >> m_force_back_right;
}

/*!
 * @brief This function sets a value in member force_front_left
 * @param _force_front_left New value for member force_front_left
 */
void idl_msg::GripperSensor_msg::force_front_left(
        int32_t _force_front_left)
{
    m_force_front_left = _force_front_left;
}

/*!
 * @brief This function returns the value of member force_front_left
 * @return Value of member force_front_left
 */
int32_t idl_msg::GripperSensor_msg::force_front_left() const
{
    return m_force_front_left;
}

/*!
 * @brief This function returns a reference to member force_front_left
 * @return Reference to member force_front_left
 */
int32_t& idl_msg::GripperSensor_msg::force_front_left()
{
    return m_force_front_left;
}

/*!
 * @brief This function sets a value in member force_front_right
 * @param _force_front_right New value for member force_front_right
 */
void idl_msg::GripperSensor_msg::force_front_right(
        int32_t _force_front_right)
{
    m_force_front_right = _force_front_right;
}

/*!
 * @brief This function returns the value of member force_front_right
 * @return Value of member force_front_right
 */
int32_t idl_msg::GripperSensor_msg::force_front_right() const
{
    return m_force_front_right;
}

/*!
 * @brief This function returns a reference to member force_front_right
 * @return Reference to member force_front_right
 */
int32_t& idl_msg::GripperSensor_msg::force_front_right()
{
    return m_force_front_right;
}

/*!
 * @brief This function sets a value in member force_back_left
 * @param _force_back_left New value for member force_back_left
 */
void idl_msg::GripperSensor_msg::force_back_left(
        int32_t _force_back_left)
{
    m_force_back_left = _force_back_left;
}

/*!
 * @brief This function returns the value of member force_back_left
 * @return Value of member force_back_left
 */
int32_t idl_msg::GripperSensor_msg::force_back_left() const
{
    return m_force_back_left;
}

/*!
 * @brief This function returns a reference to member force_back_left
 * @return Reference to member force_back_left
 */
int32_t& idl_msg::GripperSensor_msg::force_back_left()
{
    return m_force_back_left;
}

/*!
 * @brief This function sets a value in member force_back_right
 * @param _force_back_right New value for member force_back_right
 */
void idl_msg::GripperSensor_msg::force_back_right(
        int32_t _force_back_right)
{
    m_force_back_right = _force_back_right;
}

/*!
 * @brief This function returns the value of member force_back_right
 * @return Value of member force_back_right
 */
int32_t idl_msg::GripperSensor_msg::force_back_right() const
{
    return m_force_back_right;
}

/*!
 * @brief This function returns a reference to member force_back_right
 * @return Reference to member force_back_right
 */
int32_t& idl_msg::GripperSensor_msg::force_back_right()
{
    return m_force_back_right;
}


size_t idl_msg::GripperSensor_msg::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;







    return current_align;
}

bool idl_msg::GripperSensor_msg::isKeyDefined()
{
    return false;
}

void idl_msg::GripperSensor_msg::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
        
}

