// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Mocap_msg.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _IDL_MSG_MOCAP_MSG_H_
#define _IDL_MSG_MOCAP_MSG_H_

#include "Euler_angle_msg.h"
#include "Vector3f_msg.h"
#include "Header_msg.h"

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(Mocap_msg_SOURCE)
#define Mocap_msg_DllAPI __declspec( dllexport )
#else
#define Mocap_msg_DllAPI __declspec( dllimport )
#endif // Mocap_msg_SOURCE
#else
#define Mocap_msg_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define Mocap_msg_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace idl_msg {
    /*!
     * @brief This class represents the structure Mocap_msg defined by the user in the IDL file.
     * @ingroup MOCAP_MSG
     */
    class Mocap_msg
    {
    public:

        /*!
         * @brief Default constructor.
         */
        eProsima_user_DllExport Mocap_msg();

        /*!
         * @brief Default destructor.
         */
        eProsima_user_DllExport ~Mocap_msg();

        /*!
         * @brief Copy constructor.
         * @param x Reference to the object idl_msg::Mocap_msg that will be copied.
         */
        eProsima_user_DllExport Mocap_msg(
                const Mocap_msg& x);

        /*!
         * @brief Move constructor.
         * @param x Reference to the object idl_msg::Mocap_msg that will be copied.
         */
        eProsima_user_DllExport Mocap_msg(
                Mocap_msg&& x);

        /*!
         * @brief Copy assignment.
         * @param x Reference to the object idl_msg::Mocap_msg that will be copied.
         */
        eProsima_user_DllExport Mocap_msg& operator =(
                const Mocap_msg& x);

        /*!
         * @brief Move assignment.
         * @param x Reference to the object idl_msg::Mocap_msg that will be copied.
         */
        eProsima_user_DllExport Mocap_msg& operator =(
                Mocap_msg&& x);

        /*!
         * @brief Comparison operator.
         * @param x idl_msg::Mocap_msg object to compare.
         */
        eProsima_user_DllExport bool operator ==(
                const Mocap_msg& x);

        /*!
         * @brief Comparison operator.
         * @param x idl_msg::Mocap_msg object to compare.
         */
        eProsima_user_DllExport bool operator !=(
                const Mocap_msg& x);

        /*!
         * @brief This function copies the value in member header
         * @param _header New value to be copied in member header
         */
        eProsima_user_DllExport void header(
                const idl_msg::Header_msg& _header);

        /*!
         * @brief This function moves the value in member header
         * @param _header New value to be moved in member header
         */
        eProsima_user_DllExport void header(
                idl_msg::Header_msg&& _header);

        /*!
         * @brief This function returns a constant reference to member header
         * @return Constant reference to member header
         */
        eProsima_user_DllExport const idl_msg::Header_msg& header() const;

        /*!
         * @brief This function returns a reference to member header
         * @return Reference to member header
         */
        eProsima_user_DllExport idl_msg::Header_msg& header();
        /*!
         * @brief This function sets a value in member occluded
         * @param _occluded New value for member occluded
         */
        eProsima_user_DllExport void occluded(
                bool _occluded);

        /*!
         * @brief This function returns the value of member occluded
         * @return Value of member occluded
         */
        eProsima_user_DllExport bool occluded() const;

        /*!
         * @brief This function returns a reference to member occluded
         * @return Reference to member occluded
         */
        eProsima_user_DllExport bool& occluded();

        /*!
         * @brief This function copies the value in member position
         * @param _position New value to be copied in member position
         */
        eProsima_user_DllExport void position(
                const idl_msg::Vector3f_msg& _position);

        /*!
         * @brief This function moves the value in member position
         * @param _position New value to be moved in member position
         */
        eProsima_user_DllExport void position(
                idl_msg::Vector3f_msg&& _position);

        /*!
         * @brief This function returns a constant reference to member position
         * @return Constant reference to member position
         */
        eProsima_user_DllExport const idl_msg::Vector3f_msg& position() const;

        /*!
         * @brief This function returns a reference to member position
         * @return Reference to member position
         */
        eProsima_user_DllExport idl_msg::Vector3f_msg& position();
        /*!
         * @brief This function copies the value in member orientation
         * @param _orientation New value to be copied in member orientation
         */
        eProsima_user_DllExport void orientation(
                const idl_msg::Euler_angle_msg& _orientation);

        /*!
         * @brief This function moves the value in member orientation
         * @param _orientation New value to be moved in member orientation
         */
        eProsima_user_DllExport void orientation(
                idl_msg::Euler_angle_msg&& _orientation);

        /*!
         * @brief This function returns a constant reference to member orientation
         * @return Constant reference to member orientation
         */
        eProsima_user_DllExport const idl_msg::Euler_angle_msg& orientation() const;

        /*!
         * @brief This function returns a reference to member orientation
         * @return Reference to member orientation
         */
        eProsima_user_DllExport idl_msg::Euler_angle_msg& orientation();
        /*!
         * @brief This function sets a value in member latency
         * @param _latency New value for member latency
         */
        eProsima_user_DllExport void latency(
                float _latency);

        /*!
         * @brief This function returns the value of member latency
         * @return Value of member latency
         */
        eProsima_user_DllExport float latency() const;

        /*!
         * @brief This function returns a reference to member latency
         * @return Reference to member latency
         */
        eProsima_user_DllExport float& latency();


        /*!
         * @brief This function returns the maximum serialized size of an object
         * depending on the buffer alignment.
         * @param current_alignment Buffer alignment.
         * @return Maximum serialized size.
         */
        eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                size_t current_alignment = 0);

        /*!
         * @brief This function returns the serialized size of a data depending on the buffer alignment.
         * @param data Data which is calculated its serialized size.
         * @param current_alignment Buffer alignment.
         * @return Serialized size.
         */
        eProsima_user_DllExport static size_t getCdrSerializedSize(
                const idl_msg::Mocap_msg& data,
                size_t current_alignment = 0);


        /*!
         * @brief This function serializes an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void serialize(
                eprosima::fastcdr::Cdr& cdr) const;

        /*!
         * @brief This function deserializes an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void deserialize(
                eprosima::fastcdr::Cdr& cdr);



        /*!
         * @brief This function returns the maximum serialized size of the Key of an object
         * depending on the buffer alignment.
         * @param current_alignment Buffer alignment.
         * @return Maximum serialized size.
         */
        eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                size_t current_alignment = 0);

        /*!
         * @brief This function tells you if the Key has been defined for this type
         */
        eProsima_user_DllExport static bool isKeyDefined();

        /*!
         * @brief This function serializes the key members of an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void serializeKey(
                eprosima::fastcdr::Cdr& cdr) const;

    private:

        idl_msg::Header_msg m_header;
        bool m_occluded;
        idl_msg::Vector3f_msg m_position;
        idl_msg::Euler_angle_msg m_orientation;
        float m_latency;
    };
} // namespace idl_msg

#endif // _IDL_MSG_MOCAP_MSG_H_