// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MocapSegments_msg.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _IDL_MSG_MOCAPSEGMENTS_MSG_H_
#define _IDL_MSG_MOCAPSEGMENTS_MSG_H_


#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(MocapSegments_msg_SOURCE)
#define MocapSegments_msg_DllAPI __declspec( dllexport )
#else
#define MocapSegments_msg_DllAPI __declspec( dllimport )
#endif // MocapSegments_msg_SOURCE
#else
#define MocapSegments_msg_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define MocapSegments_msg_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace idl_msg {
    /*!
     * @brief This class represents the structure MocapSegments_msg defined by the user in the IDL file.
     * @ingroup MOCAPSEGMENTS_MSG
     */
    class MocapSegments_msg
    {
    public:

        /*!
         * @brief Default constructor.
         */
        eProsima_user_DllExport MocapSegments_msg();

        /*!
         * @brief Default destructor.
         */
        eProsima_user_DllExport ~MocapSegments_msg();

        /*!
         * @brief Copy constructor.
         * @param x Reference to the object idl_msg::MocapSegments_msg that will be copied.
         */
        eProsima_user_DllExport MocapSegments_msg(
                const MocapSegments_msg& x);

        /*!
         * @brief Move constructor.
         * @param x Reference to the object idl_msg::MocapSegments_msg that will be copied.
         */
        eProsima_user_DllExport MocapSegments_msg(
                MocapSegments_msg&& x);

        /*!
         * @brief Copy assignment.
         * @param x Reference to the object idl_msg::MocapSegments_msg that will be copied.
         */
        eProsima_user_DllExport MocapSegments_msg& operator =(
                const MocapSegments_msg& x);

        /*!
         * @brief Move assignment.
         * @param x Reference to the object idl_msg::MocapSegments_msg that will be copied.
         */
        eProsima_user_DllExport MocapSegments_msg& operator =(
                MocapSegments_msg&& x);

        /*!
         * @brief Comparison operator.
         * @param x idl_msg::MocapSegments_msg object to compare.
         */
        eProsima_user_DllExport bool operator ==(
                const MocapSegments_msg& x);

        /*!
         * @brief Comparison operator.
         * @param x idl_msg::MocapSegments_msg object to compare.
         */
        eProsima_user_DllExport bool operator !=(
                const MocapSegments_msg& x);

        /*!
         * @brief This function copies the value in member object_name
         * @param _object_name New value to be copied in member object_name
         */
        eProsima_user_DllExport void object_name(
                const std::string& _object_name);

        /*!
         * @brief This function moves the value in member object_name
         * @param _object_name New value to be moved in member object_name
         */
        eProsima_user_DllExport void object_name(
                std::string&& _object_name);

        /*!
         * @brief This function returns a constant reference to member object_name
         * @return Constant reference to member object_name
         */
        eProsima_user_DllExport const std::string& object_name() const;

        /*!
         * @brief This function returns a reference to member object_name
         * @return Reference to member object_name
         */
        eProsima_user_DllExport std::string& object_name();
        /*!
         * @brief This function copies the value in member segment_x
         * @param _segment_x New value to be copied in member segment_x
         */
        eProsima_user_DllExport void segment_x(
                const std::array<float, 10>& _segment_x);

        /*!
         * @brief This function moves the value in member segment_x
         * @param _segment_x New value to be moved in member segment_x
         */
        eProsima_user_DllExport void segment_x(
                std::array<float, 10>&& _segment_x);

        /*!
         * @brief This function returns a constant reference to member segment_x
         * @return Constant reference to member segment_x
         */
        eProsima_user_DllExport const std::array<float, 10>& segment_x() const;

        /*!
         * @brief This function returns a reference to member segment_x
         * @return Reference to member segment_x
         */
        eProsima_user_DllExport std::array<float, 10>& segment_x();
        /*!
         * @brief This function copies the value in member segment_y
         * @param _segment_y New value to be copied in member segment_y
         */
        eProsima_user_DllExport void segment_y(
                const std::array<float, 10>& _segment_y);

        /*!
         * @brief This function moves the value in member segment_y
         * @param _segment_y New value to be moved in member segment_y
         */
        eProsima_user_DllExport void segment_y(
                std::array<float, 10>&& _segment_y);

        /*!
         * @brief This function returns a constant reference to member segment_y
         * @return Constant reference to member segment_y
         */
        eProsima_user_DllExport const std::array<float, 10>& segment_y() const;

        /*!
         * @brief This function returns a reference to member segment_y
         * @return Reference to member segment_y
         */
        eProsima_user_DllExport std::array<float, 10>& segment_y();
        /*!
         * @brief This function copies the value in member segment_z
         * @param _segment_z New value to be copied in member segment_z
         */
        eProsima_user_DllExport void segment_z(
                const std::array<float, 10>& _segment_z);

        /*!
         * @brief This function moves the value in member segment_z
         * @param _segment_z New value to be moved in member segment_z
         */
        eProsima_user_DllExport void segment_z(
                std::array<float, 10>&& _segment_z);

        /*!
         * @brief This function returns a constant reference to member segment_z
         * @return Constant reference to member segment_z
         */
        eProsima_user_DllExport const std::array<float, 10>& segment_z() const;

        /*!
         * @brief This function returns a reference to member segment_z
         * @return Reference to member segment_z
         */
        eProsima_user_DllExport std::array<float, 10>& segment_z();

        /*!
         * @brief This function returns the maximum serialized size of an object
         * depending on the buffer alignment.
         * @param current_alignment Buffer alignment.
         * @return Maximum serialized size.
         */
        eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                size_t current_alignment = 0);

        /*!
         * @brief This function returns the serialized size of a data depending on the buffer alignment.
         * @param data Data which is calculated its serialized size.
         * @param current_alignment Buffer alignment.
         * @return Serialized size.
         */
        eProsima_user_DllExport static size_t getCdrSerializedSize(
                const idl_msg::MocapSegments_msg& data,
                size_t current_alignment = 0);


        /*!
         * @brief This function serializes an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void serialize(
                eprosima::fastcdr::Cdr& cdr) const;

        /*!
         * @brief This function deserializes an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void deserialize(
                eprosima::fastcdr::Cdr& cdr);



        /*!
         * @brief This function returns the maximum serialized size of the Key of an object
         * depending on the buffer alignment.
         * @param current_alignment Buffer alignment.
         * @return Maximum serialized size.
         */
        eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                size_t current_alignment = 0);

        /*!
         * @brief This function tells you if the Key has been defined for this type
         */
        eProsima_user_DllExport static bool isKeyDefined();

        /*!
         * @brief This function serializes the key members of an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void serializeKey(
                eprosima::fastcdr::Cdr& cdr) const;

    private:

        std::string m_object_name;
        std::array<float, 10> m_segment_x;
        std::array<float, 10> m_segment_y;
        std::array<float, 10> m_segment_z;
    };
} // namespace idl_msg

#endif // _IDL_MSG_MOCAPSEGMENTS_MSG_H_